#!/bin/bash

npm install cypress

mkdir -p ./cypress/integration

echo "describe('My First Test', function() {
  it('Can navigate to subpage called env', function() {
    cy.visit('https://example.cypress.io')
    
    cy.url().should('include', '/cypress-api/env')
  })
})" > './cypress/integration/cypress_test.js'


npm run cypress

exit 0